%
% This code reads in the data file generated by calc_sRK4.m. Then it
% plots the two components of the numerical solution: position and velocity.
%
clear
figure(2);
clf reset
%
set(gcf,'position',[100,50,500,600])
set(gcf,'paperposition',[0.5,0.5,7.5,10.0]) 
%
load data_sRK4
%
axes('position',[0.18,0.56,0.74,0.36])
plot(t,w(1:nstep+1,1),'k-','linewidth',1.0)
hold on
plot(t,w(1:nstep+1,2),'b--','linewidth',1.0)
set(gca,'fontsize',14)
axis([0,40,-1.1,1.1])
set(gca,'xtick',[0:10:40])
set(gca,'ytick',[-1:0.5:1])
xlabel('t')
ylabel('w')
title('Numerical solution by RK4')
h1=legend('Position','Velocity',1);
set(h1,'fontsize',12)
%
axes('position',[0.18,0.09,0.74,0.36])
plot(w(1:nstep+1,1),w(1:nstep+1,2),'b-')
set(gca,'fontsize',14)
axis equal
axis([-1.1,1.1,-1.1,1.1])
set(gca,'xtick',[-1:0.5:1])
set(gca,'ytick',[-1:0.5:1])
xlabel('Position')
ylabel('Velocity')
%
%
